server {
    listen 80;
    listen [::]:80;
    server_name auth.cqaiclub.asia auth-admin.cqaiclub.asia;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name auth.cqaiclub.asia;

    ssl_certificate /etc/nginx/ssl/cqai-logto.fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/cqai-logto.key;
    include /etc/letsencrypt/options-ssl-nginx.conf;

    client_max_body_size 20m;

    location / {
        proxy_pass http://127.0.0.1:3011;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 10s;
        proxy_read_timeout 120s;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name auth-admin.cqaiclub.asia;

    ssl_certificate /etc/nginx/ssl/cqai-logto.fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/cqai-logto.key;
    include /etc/letsencrypt/options-ssl-nginx.conf;

    client_max_body_size 20m;

    location / {
        proxy_pass http://127.0.0.1:3012;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 10s;
        proxy_read_timeout 120s;
    }
}
